/**
 ******************************************************************************
 * @file    log.c
 * @author  Auto-generated by AI
 * @brief   STM32H7 & FreeRTOS 高性能日志库实现
 * @note    输出格式: [颜色][级别][时间戳][任务名][文件:行号] 消息\r\n
 ******************************************************************************
 */

#include "log.h"
#include "usart.h"
#include "semphr.h"
#include <stdarg.h>
#include <string.h>

/* ============================================================================
 * 外部变量
 * ============================================================================
 */

extern UART_HandleTypeDef huart1;  /**< UART1句柄,用于日志输出 */

/* ============================================================================
 * 私有变量
 * ============================================================================
 */

/** @brief 线程安全互斥锁 */
static SemaphoreHandle_t xLogMutex = NULL;

/** @brief 单行日志格式化缓冲区 */
static char log_line_buf[LOG_MAX_LINE_LEN];

/* ============================================================================
 * 私有宏定义
 * ============================================================================
 */

/** @brief 安全计算剩余缓冲区空间 */
#define REMAINING(len) ((len) > 0 ? (len) : 0)

/* ============================================================================
 * 私有函数声明
 * ============================================================================
 */

/**
 * @brief   计算缓冲区剩余空间
 * @param   offset 当前已使用的缓冲区长度
 * @return  剩余可用字节数
 */
static inline uint32_t log_remaining(uint32_t offset);

/**
 * @brief   安全追加格式化字符串到缓冲区
 * @param   buf    缓冲区指针(会被更新)
 * @param   remain 剩余长度(会被更新)
 * @param   fmt    格式化字符串
 * @param   args   可变参数列表
 */
static void log_append_va(char** buf, uint32_t* remain,
                          const char* fmt, va_list args);

/* ============================================================================
 * 内部辅助函数实现
 * ============================================================================
 */

static inline uint32_t log_remaining(uint32_t offset)
{
    if (offset >= LOG_MAX_LINE_LEN) return 0;
    return LOG_MAX_LINE_LEN - offset;
}

/**
 * @brief 安全地使用格式化字符串追加内容到缓冲区
 * @note  如果缓冲区空间不足,会标记remain为0并截断
 */
static void log_append_va(char** buf, uint32_t* remain, const char* fmt, va_list args)
{
    if (*remain == 0) return;

    int written = vsnprintf(*buf, *remain, fmt, args);

    if (written > 0 && (uint32_t)written < *remain) {
        *buf += written;
        *remain -= written;
    } else {
        *remain = 0;
    }
}

/**
 * @brief 安全地追加带可变参数的格式化字符串
 * @param  buf    缓冲区指针(会被更新)
 * @param  remain 剩余长度(会被更新)
 * @param  fmt    格式化字符串
 */
static void log_append(char** buf, uint32_t* remain, const char* fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    log_append_va(buf, remain, fmt, args);
    va_end(args);
}

/* ============================================================================
 * 公共接口实现
 * ============================================================================
 */

/**
 * @brief  初始化日志系统
 * @retval 0:成功, -1:互斥锁创建失败
 * @note   可多次安全调用(幂等操作)
 */
int log_init(void)
{
    if (xLogMutex == NULL) {
        xLogMutex = xSemaphoreCreateMutex();
    }
    return (xLogMutex != NULL) ? 0 : -1;
}

/**
 * @brief  写入一条日志消息
 * @param  level 日志级别
 * @param  file  源文件名
 * @param  line  源文件行号
 * @param  func  函数名
 * @param  fmt   printf风格格式化字符串
 * @param  ...   格式化参数
 *
 * @note   输出格式: [颜色][级别][tick][任务名][文件:行号] 消息\r\n
 *         - 如果调度器已启动,会获取互斥锁保证线程安全
 *         - 使用vsnprintf格式化,防止缓冲区溢出
 *         - 获取锁时永久阻塞(portMAX_DELAY)
 */
void log_write(log_level_t level, const char* file, int line,
               const char* func, const char* fmt, ...)
{
    /* 缓存调度器状态,避免重复调用 */
    BaseType_t scheduler_started = (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED);

    /* 校验日志级别有效性 */
    if (level <= LOG_LEVEL_NONE || level > LOG_LEVEL_ALL) return;

    /* 如果调度器运行中但互斥锁未初始化,则退出 */
    if (xLogMutex == NULL && scheduler_started) return;

    /* 获取互斥锁 */
    if (scheduler_started) {
        xSemaphoreTake(xLogMutex, portMAX_DELAY);
    }

    /* 初始化缓冲区指针 */
    char* buf = log_line_buf;
    uint32_t remain = LOG_MAX_LINE_LEN;

    /* 根据严重级别确定字符串和颜色 */
    const char* level_str = "";
    const char* color_str = LOG_CLR_RESET;

    switch (level) {
        case LOG_LEVEL_FATAL: level_str = "FATAL"; color_str = LOG_CLR_FATAL; break;
        case LOG_LEVEL_ERROR: level_str = "ERROR"; color_str = LOG_CLR_ERROR; break;
        case LOG_LEVEL_WARN:  level_str = "WARN "; color_str = LOG_CLR_WARN;  break;
        case LOG_LEVEL_INFO:  level_str = "INFO "; color_str = LOG_CLR_INFO;  break;
        case LOG_LEVEL_DEBUG: level_str = "DEBUG"; color_str = LOG_CLR_DEBUG; break;
        default: break;
    }

    /* 构建日志头: [颜色][级别] */
    log_append(&buf, &remain, "%s[%s]", color_str, level_str);

#if LOG_USE_TIMESTAMP
    /* 追加系统tick时间戳 */
    log_append(&buf, &remain, "[%08u]", (unsigned int)xTaskGetTickCount());
#endif

#if LOG_USE_TASK_NAME
    /* 追加当前任务名称(调度器未启动时显示"System") */
    if (scheduler_started) {
        const char* task_name = pcTaskGetName(NULL);
        if (task_name == NULL) task_name = "Unknown";
        log_append(&buf, &remain, "[%s]", task_name);
    } else {
        log_append(&buf, &remain, "[System]");
    }
#endif

#if LOG_USE_FILE_LINE
    /* 从完整路径中提取文件名,追加[file:line] */
    const char* filename = strrchr(file, '\\') ? strrchr(file, '\\') + 1 : file;
    log_append(&buf, &remain, "[%s:%d] ", filename, line);
#endif

    /* 格式化实际的消息内容 */
    va_list args;
    va_start(args, fmt);
    int written = vsnprintf(buf, remain, fmt, args);
    va_end(args);

    if (written > 0 && (uint32_t)written < remain) {
        buf += written;
        remain -= written;
    } else {
        buf += remain;
        remain = 0;
    }

    /* 追加颜色重置和换行符 */
    log_append(&buf, &remain, "%s\r\n", LOG_CLR_RESET);

    /* 通过UART发送完整日志行 */
    uint32_t total_len = LOG_MAX_LINE_LEN - remain;
    HAL_UART_Transmit(&huart1, (uint8_t*)log_line_buf, total_len, HAL_MAX_DELAY);

    /* 释放互斥锁 */
    if (scheduler_started) {
        xSemaphoreGive(xLogMutex);
    }
}

/**
 * @brief  以十六进制dump格式输出内存区域
 * @param  label 描述标签
 * @param  data  内存起始地址
 * @param  len   内存长度(字节)
 *
 * @note   输出格式:
 *         --- label (len:N) ---
 *         XX XX XX XX ... XX XX\r\n
 *         ... (每行16字节)
 *         ------------------
 */
void log_hexdump(const char* label, const void* data, uint32_t len)
{
    BaseType_t scheduler_started = (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED);

    /* 调度器运行中但互斥锁未初始化则退出 */
    if (xLogMutex == NULL && scheduler_started) return;

    /* 获取互斥锁 */
    if (scheduler_started) {
        xSemaphoreTake(xLogMutex, portMAX_DELAY);
    }

    char* buf = log_line_buf;
    uint32_t remain = LOG_MAX_LINE_LEN;

    /* 打印头部 */
    log_append(&buf, &remain, "--- %s (len:%u) ---\r\n", label, (unsigned int)len);

    /* 打印十六进制字节,每行16个 */
    const uint8_t* p = (const uint8_t*)data;
    for (uint32_t i = 0; i < len && remain > 0; i++) {
        int n = snprintf(buf, remain, "%02X ", p[i]);
        if (n > 0 && n < (int)remain) {
            buf += n;
            remain -= n;
        } else {
            break;
        }
        /* 每16字节换行 */
        if ((i + 1) % 16 == 0 && remain > 0) {
            n = snprintf(buf, remain, "\r\n");
            if (n > 0 && n < (int)remain) {
                buf += n;
                remain -= n;
            } else {
                break;
            }
        }
    }

    /* 如果还有空间则打印尾部 */
    if (remain > 0) {
        snprintf(buf, remain, "\r\n------------------\r\n");
    }

    /* 通过UART发送完整hexdump */
    uint32_t total_len = LOG_MAX_LINE_LEN - remain;
    HAL_UART_Transmit(&huart1, (uint8_t*)log_line_buf, total_len, HAL_MAX_DELAY);

    /* 释放互斥锁 */
    if (scheduler_started) {
        xSemaphoreGive(xLogMutex);
    }
}