/**
 ******************************************************************************
 * @file    log.h
 * @author  Auto-generated by AI
 * @brief   STM32H7 & FreeRTOS 高性能日志库
 * @note    特性：颜色输出、时间戳、任务名、文件行号、十六进制dump
 ******************************************************************************
 */

#ifndef __LOG_H_
#define __LOG_H_

#include <stdio.h>
#include <stdint.h>
#include "FreeRTOS.h"
#include "task.h"

/* ============================================================================
 * 配置项
 * ============================================================================ */

/** @brief 启用ANSI颜色代码(需要终端支持) */
#define LOG_USE_COLOR 1

/** @brief 在日志行中包含系统tick时间戳 [tick count] */
#define LOG_USE_TIMESTAMP 1

/** @brief 在日志行中包含当前FreeRTOS任务名称 [task name] */
#define LOG_USE_TASK_NAME 1

/** @brief 在日志行中包含源文件名和行号 [file:line] */
#define LOG_USE_FILE_LINE 1

/** @brief 内部异步缓冲区大小(预留,当前未使用) */
#define LOG_ASYNC_BUFFER_SIZE 2048

/** @brief 单条日志最大长度(字节) */
#define LOG_MAX_LINE_LEN 256

/* ============================================================================
 * 日志级别定义
 * ============================================================================
 * 数值越大,严重程度越低。LOG_CONFIG_LEVEL 在编译时过滤低于该级别的消息。
 */
typedef enum
{
    LOG_LEVEL_NONE = 0, /**< 关闭所有日志 */
    LOG_LEVEL_FATAL,    /**< 致命错误,系统即将停止 */
    LOG_LEVEL_ERROR,    /**< 可恢复的错误 */
    LOG_LEVEL_WARN,     /**< 警告信息 */
    LOG_LEVEL_INFO,     /**< 一般信息 */
    LOG_LEVEL_DEBUG,    /**< 调试信息 */
    LOG_LEVEL_ALL       /**< 所有级别(最低优先级) */
} log_level_t;

/** @brief 编译时日志级别过滤阈值(默认:DEBUG,输出所有级别) */
#ifndef LOG_CONFIG_LEVEL
#define LOG_CONFIG_LEVEL LOG_LEVEL_DEBUG
#endif

/* ============================================================================
 * ANSI颜色代码
 * ============================================================================
 * 用于终端显示时按严重级别着色
 */
#if LOG_USE_COLOR
#define LOG_CLR_RESET "\033[0m"    /**< 重置为默认颜色 */
#define LOG_CLR_FATAL "\033[1;31m" /**< 粗体红色 - FATAL级别 */
#define LOG_CLR_ERROR "\033[0;31m" /**< 红色 - ERROR级别 */
#define LOG_CLR_WARN "\033[0;33m"  /**< 黄色 - WARN级别 */
#define LOG_CLR_INFO "\033[0;32m"  /**< 绿色 - INFO级别 */
#define LOG_CLR_DEBUG "\033[0;36m" /**< 青色 - DEBUG级别 */
#else
#define LOG_CLR_RESET ""
#define LOG_CLR_FATAL ""
#define LOG_CLR_ERROR ""
#define LOG_CLR_WARN ""
#define LOG_CLR_INFO ""
#define LOG_CLR_DEBUG ""
#endif

/* ============================================================================
 * 公共接口
 * ============================================================================
 */

/**
 * @brief  初始化日志系统
 * @retval 0:成功, -1:互斥锁创建失败
 * @note   必须在使用日志功能前调用
 */
int log_init(void);

/**
 * @brief  核心日志写入函数(通常通过宏调用)
 * @param  level  日志级别
 * @param  file   源文件名(__FILE__)
 * @param  line   源文件行号(__LINE__)
 * @param  func   函数名(__FUNCTION__)
 * @param  fmt    printf风格格式化字符串
 * @param  ...    格式化参数
 */
void log_write(log_level_t level, const char *file, int line,
               const char *func, const char *fmt, ...);

/**
 * @brief  十六进制内存dump
 * @param  label  内存区域的描述标签
 * @param  data   内存起始地址
 * @param  len    内存长度(字节)
 * @note   输出格式: 每行16字节,包含ASCII表示
 */
void log_hexdump(const char *label, const void *data, uint32_t len);

/* ============================================================================
 * 日志宏
 * ============================================================================
 * 各级别的便捷宏,自动捕获file/line/function信息。
 * 消息在编译时根据LOG_CONFIG_LEVEL进行过滤。
 */

/** @brief 记录FATAL级别日志(最高严重性) */
#if (LOG_CONFIG_LEVEL >= LOG_LEVEL_FATAL)
#define LOG_F(fmt, ...) \
    log_write(LOG_LEVEL_FATAL, __FILE__, __LINE__, __FUNCTION__, fmt, ##__VA_ARGS__)
#else
#define LOG_F(fmt, ...)
#endif

/** @brief 记录ERROR级别日志 */
#if (LOG_CONFIG_LEVEL >= LOG_LEVEL_ERROR)
#define LOG_E(fmt, ...) \
    log_write(LOG_LEVEL_ERROR, __FILE__, __LINE__, __FUNCTION__, fmt, ##__VA_ARGS__)
#else
#define LOG_E(fmt, ...)
#endif

/** @brief 记录WARN级别日志 */
#if (LOG_CONFIG_LEVEL >= LOG_LEVEL_WARN)
#define LOG_W(fmt, ...) \
    log_write(LOG_LEVEL_WARN, __FILE__, __LINE__, __FUNCTION__, fmt, ##__VA_ARGS__)
#else
#define LOG_W(fmt, ...)
#endif

/** @brief 记录INFO级别日志 */
#if (LOG_CONFIG_LEVEL >= LOG_LEVEL_INFO)
#define LOG_I(fmt, ...) \
    log_write(LOG_LEVEL_INFO, __FILE__, __LINE__, __FUNCTION__, fmt, ##__VA_ARGS__)
#else
#define LOG_I(fmt, ...)
#endif

/** @brief 记录DEBUG级别日志(默认最低级别) */
#if (LOG_CONFIG_LEVEL >= LOG_LEVEL_DEBUG)
#define LOG_D(fmt, ...) \
    log_write(LOG_LEVEL_DEBUG, __FILE__, __LINE__, __FUNCTION__, fmt, ##__VA_ARGS__)
#else
#define LOG_D(fmt, ...)
#endif

#endif /* __LOG_H_ */